apiVersion: v1
kind: Secret
metadata:
  name: app-1
type: Opaque
data:
  uname: YXBwMQo=
  pwd: YXBwMQo=
---
apiVersion: v1
kind: Secret
metadata:
  name: app-2
type: Opaque
data:
  username: YXBwMgo=
  password: YXBwMgo=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secretReader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  resourceNames: ["app-1"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: secretReader
  namespace: default
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: app-1 # "name" is case sensitive
  namespace: default
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: secretReader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
kind: Pod
apiVersion: v1
metadata:
  name: pod-1
  labels:
    app: app-1
spec:
  # one pod can contain multiple containers
  serviceAccountName: app-1
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: app-1
    - secretRef:
        name: app-2

