apiVersion: v1
kind: Secret
metadata:
  name: app-1
type: Opaque
data:
  username: YXBwMQo=
  password: YXBwMQo=
---
apiVersion: v1
kind: Secret
metadata:
  name: app-2
type: Opaque
data:
  username: YXBwMgo=
  password: YXBwMgo=
---
kind: Pod
apiVersion: v1
metadata:
  name: pod-1
  labels:
    app: app-1
spec:
  # one pod can contain multiple containers
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: app-1
    - secretRef:
        name: app-2

